### PR TITLE
trlteduos: bring up of O

### PR DESCRIPTION
**Pull request by ripee**
* Hacked mdm_helper and mdm_helper_proxy blobs and added md5sums to device tree
* Hacked libsecrils
* Rearranged blobs as per tblte and moved the appropriate ones to /vendor

### CODE REVIEW

**Comment by micky387** [comment]
@ ripee
please do not add duplicate pull request, thanks

https://github.com/samsung-apq8084/proprietary_vendor_samsung/pull/8/commits
https://github.com/samsung-apq8084/proprietary_vendor_samsung/pull/9

**Comment by ripee** [comment]
What are you talking about? @chirs241097 made his pull request independently of me because he used my changes before I created my pull request. Please read what I wrote under his request.

Edit: chirs241097 hasn't merged my duos blobs, perhaps that's why he is getting SIM 2 errors.

**Comment by micky387** [comment]
@ripee , as i told you earlier  edit your push request. delete this commits https://github.com/samsung-apq8084/proprietary_vendor_samsung/pull/10/commits/dbac5a43e36b8527bd36cc4053ec746c65918f3a
I had already applied earlier and it's merged now

**Comment by ripee** [comment]
Earlier, you didn't specify which commit was duplicated, you just linked to chirs's outdated blob fork. I just assumed you meant what chirs is working on.

I'll do that as soon as I can, thanks for following up :)

**Comment by chirs241097** [comment]
@ripee I don't think the SIM 2 issue is related to ~~proprietary blobs~~ me not merging your blobs... I produced a build with your proprietary tree today but it didn't work either. Did you read my radio log?

**Comment by ripee** [comment]
So in that case let's merge my blobs so that they will be at the same level as the tblte and trlte blobs. It's getting more and more complicated to keep up with trying to merge micky's updates in the blobs repo, and then I'd have to revert those changes out of my blobs before I could submit anything for merging here.

**Comment by github-cygwin** [comment]
Overridden by pull request #12

**Pull request closed without merging**
