### PR TITLE
Use blobs with fixed paths from N9100ZCS1DQH1.

### PR DESCRIPTION
**Pull request by chirs241097**
Also removed unused blobs (this change is actually from @ripee).
Tested and works on SM-N9100.
libsec-ril-09w.so and libsec-ril-dsds-09w.so are not updated because those are for SM-N9109W. They still got the libprotobuf path patch though.
If this got merged, the md5sum in device/samsung/trlteduos/device-proprietary-files.txt would need updating.

### CODE REVIEW

**Comment by micky387** [comment]
if it working ,ok
can you update device-proprietary-files.txt  too with md5sum for hacked blobs ?

**Comment by chirs241097** [comment]
I would update the md5sum after ripee's new trlteduos tree gets merged.
Just being curious, but should libsec-ril* have md5sum with them? These are hacked blobs too.

**Comment by micky387** [comment]
yes ,you have right. i will add this later

**Comment by github-cygwin** [comment]
Why are these blobs hacked?  Why not fix the problem with symlinks instead, e.g.
https://github.com/samsung-apq8084/android_device_samsung_lentis-common/commit/b49146873f1115e0405227c7a073c5e425dac3c6

This way you can still update the blobs if Samsung pushes new ones (even if it's pretty unlikely for some devices).

Corinna

**Comment by chirs241097** [comment]
That's also a viable solution, but what if libprotobuf updated with new symbols? Executables linked against the new version may simply fail then.

**Comment by github-cygwin** [comment]
That *may* happen with libprotobuf-cpp-full.so, but not with the other blobs.  And even for libprotobuf-cpp-full.so, I doubt this will occur prior to Android P.

**Comment by chirs241097** [comment]
Well, as the current "hack" is rather easy -- just changing the reference to libprotobuf-cpp-full.so to another path. It should be easily applied to further updates of the blobs from Samsung with sed or even a hex editor. So personally I still prefer the current solution.

**Comment by underscoremone** [comment]
Fine for me.. but please keep the prop-files.txt in the device tree up to date...

@chirs241097 have a look at https://github.com/underscoremone/android_device_samsung_trlteduos/tree/lineage-15.1 and https://github.com/underscoremone/android_device_samsung_apq8084-common/commit/fdb41d6da41e28bbd0c17ebb2ac53a6622829cf9

It may help with the second sim.. I didn't check everything yet and didn't try to build, so you probably want to double check before building.

@github-cygwin if it helps the trlteduos guys and we want to merge the apq8084 patch linked above, it'll be required to patch all the other devices with https://github.com/underscoremone/android_device_samsung_trlteduos/commit/05c15b81279db3f48711aede9691fb0fd074ff8f but using the "single" path.

**Comment by github-cygwin** [comment]
@underscoremone, I don't quite see how patching binary blobs vs. adding symlinks is related to the SIM slot patch.  Looks like an entirely different issue to me.

**Comment by micky387** [comment]
@github-cygwin : we can use https://github.com/LineageOS/android_device_samsung_klte-common/commit/0b73a22c277cdd83c9147faf3b078231812eca42#diff-594930765406fba887f66e34b0e91bc7
for reference

**Comment by underscoremone** [comment]
@github-cygwin 
Because it is entirely different..
I've just added a little extra to point the trlteduos guys to a possible help for their second sim (unrelated to this patch), mentioning you just because if it helps them it will require changes to the other devices too.
Going back to this commit, as said before, for me is fine patching the binary blobs but keeping up to date the blobs list in the device tree.

**Comment by ripee** [comment]
Which md5sums are you talking about, @micky387 and @chirs241097? I generated them myself after hacking and updated the values from spr, which I only left in place so I would know what to overwrite.

**Comment by chirs241097** [comment]
@ripee This commit includes "hacked" blobs from the latest stock firmware for SM-N9100 so the md5sum for `mdm_helper` and `mdm_helper_proxy` in `device-proprietary-files.txt` would need updating if it gets merged. I also mentioned that `libsec-ril*` should also have their md5sum appended in `device-proprietary-files.txt` (even if this commit is not merged) because those blobs are also modified.
@micky387 I manually included ripee's changes when creating the fork so it's probably a better idea to merge his changes and rebase mine on top of that.

**Comment by github-cygwin** [comment]
Overriden by pull request #12

**Pull request closed without merging**
